### ISSUE TITLE
Support multiple address and port bindings

### ISSUE THREAD

**Issue by hirikarate** [yyyar/gobetween#109]
In my Docker Swarm, I have several services, each serves different API endpoints. Eg:
- auth.example.com
- registry.example.com
- admin.example.com

And of course each has some replicas to be load-balanced by Gobetween.

Currently, according to the limited examples on official documentation, I can only:
- bind to only one address
- filter with only one label and only one private port.

```
[servers.mydomain]
bind = "auth.example.com"
protocol = "tcp"
<something else>

  [servers.mydomain.discovery]
    kind = "docker"
    docker_endpoint = "http://localhost:2375"  # Docker / Swarm API    
    docker_container_label = "api=true"  # only one label supported
    docker_container_private_port = 80   # only one port supported
```
My question is: How can I bind Gobetween to multiple addresses? With each address, how can I filter with multiple labels and ports?

Thank you!

**Comment by yyyar** [comment]
Hi @hirikarate,

Since gobetween is L4, to make it work with different "virtual" domains (that is information available in L7, actually) you can either:

**Option (1)** Create separate [server] section per your domain, if you have network interfaces (ip address) per each of them (3 in total for your case):

```
[servers.auth]
bind = "<auth_ip_address>:80"
protocol = "tcp"

  [servers.auth.discovery]
    kind = "docker"
    docker_endpoint = "http://localhost:2375"   
    docker_container_label = "service=auth"   
    docker_container_private_port = 80

[servers.registry]
bind = "<registry_ip_address>:80"
protocol = "tcp"

  [servers.registry.discovery]
    kind = "docker"
    docker_endpoint = "http://localhost:2375"   
    docker_container_label = "service=registry"   
    docker_container_private_port = 80

[servers.admin]
bind = "<admin_ip_address>:80"
protocol = "tcp"

  [servers.admin.discovery]
    kind = "docker"
    docker_endpoint = "http://localhost:2375"   
    docker_container_label = "service=admin"   
    docker_container_private_port = 80
```

And run your containers with appropriate label "service=..." to differentiate them.
`$ docker run --label service=admin myadminimage myprogram`
`$ docker run --label service=registry myregistryimage myprogram`
`$ docker run --label service=auth myauthimage myprogram`

**Option (2)** Use SNI to balance based on provided domain name, if your backends use TLS/HTTPS. You need only 1 network interface / ip address in this case:

```
[servers.example]
bind = "0.0.0.0:443"
protocol = "tcp"

 [servers.example.sni] 
 read_timeout = "2s"
 hostname_matching_strategy = "exact" 
 unexpected_hostname_strategy = "reject" 

  [servers.example.discovery]
    kind = "docker"
    docker_endpoint = "http://localhost:2375"   
    docker_container_private_port = 443
```

And use "sni" label to specify container domain name while running it, for example:
`$ docker run --label sni=admin.example.com myadminimage myprogram`
`$ docker run --label sni=registry.example.com myregistryimage myprogram`
`$ docker run --label sni=auth.example.com myauthimage myprogram`

Let us know if you'll have any success with your configuration.
Thanks!

**Comment by hirikarate** [comment]
This is my `gobetween.toml` (detail below) and the service keeps yelling: **"(server.handle): No matching sni found, rejecting due to 'reject' unexpected hostname strategy"**

- The upstream service is Portainer (a Golang webapp) with port mapping as 9000:9000 and label "sni=example.com" (label attached to container, not to the service itself). It is already accessible via "http://example.com:9000"
- I tried with both self-signed certificates "example.com" and "*.example.com".
- Not accessible via "https://example.com" although the firewall is allowing ports 9000, 80 and 443.
- I deploy "gobetween" as a Docker Swarm service, the "service create" command must include `-v //var/run/docker.sock:/var/run/docker.sock` for the discovery to work, `http://localhost:2375` just doesn't work for me. (Took me some time to figure it out. I recommend adding this to documentation)

```
[servers]
[servers.example]
bind = "0.0.0.0:443"
protocol = "tls" 
balance = "leastconn"
  
  [servers.example.tls]
  cert_path = "/path/to/ssl/server.crt"
  key_path = "/path/to/ssl/server.key"
  min_version = "tls1"
  max_version = "tls1.2"
  ciphers = []
  prefer_server_ciphers = false
  session_tickets = true 

  [servers.example.sni] 
  read_timeout = "2s"
  hostname_matching_strategy = "exact" 
  unexpected_hostname_strategy = "reject"

  [servers.example.discovery] 
  kind = "docker"
  docker_endpoint = "unix:///var/run/docker.sock"
  docker_container_private_port = 9000

  [servers.example.healthcheck]
  fails = 1        
  passes = 1
  interval = "2s"    
  timeout = "1s"        
  kind = "ping"
```

For ease of reproduction, this is my `docker-compose.yml`

```
version: '3.2'

networks:
  gennet: 
    external: true

volumes:
  gobetween-vol:
    external: true

services:
  portainer:
    image: "portainer/portainer"
    command: -H unix:///var/run/docker.sock
    ports:  
      - 9000:9000
    networks:
      - gennet
    labels: 
      - "sni=example.com"
    volumes:
      - type: bind
        source: //var/run/docker.sock
        target: /var/run/docker.sock

   gobetween:
    image: "yyyar/gobetween"
    networks:
      - gennet
    ports:
      - 80:80
      - 443:443
    volumes:
      - type: bind
        source: //var/run/docker.sock
        target: /var/run/docker.sock
      - type: volume
        source: gobetween-vol
        target: /etc/gobetween/conf
```

This is file `deploy.sh`:

```
#!/bin/bash
docker network create -d overlay gennet;
docker volume create --name=gobetween-vol;
cp ./gobetween.toml /var/lib/docker/volumes/gobetween-test-vol/_data

docker stack deploy -c docker-compose.yml "stackname"
sleep 3
echo "Services created successfully."
docker service ls
```

Make sure 3 files `gobetween.toml`, `docker-compose.yml` and `deploy.sh` are in same location.

Make sure to change domain name in service label and paths to SSL cert files.

Make sure Docker Swarm is [initialized](https://docs.docker.com/engine/swarm/swarm-tutorial/create-swarm/) (`docker swarm init --advertise-addr <IP_ADDRESS>`)

Exec `sudo bash ./deploy.sh` (you may want to `sudo chmod +x ./deploy.sh`)

View gobetween log with `docker service logs stackname_gobetween`

Finally, if you can access Portainer via "http://example.com:9000" (don't forget firewall port) or "http://<IP_ADDRESS>:9000" then you are good.

*Target*: How to make it accessible via "https://example.com"?

Clean up: Removes all services `docker service rm $(docker service ls -q)`

Please give your thoughts. Thank you!
