### ISSUE TITLE
Support multiple discoveries per server

### ISSUE THREAD

**Issue by jtopjian** [yyyar/gobetween#112]
Hi all,

Now that 0.5.0 has been released with LXD support, I wanted to revisit adding the ability to support multiple LXD plugins per server entry in gobetween. I created an example of this in https://github.com/yyyar/gobetween/pull/90 but closed it because I felt the design needed further discussion.

This is not specific to LXD, though. The reason I want to first discuss this is because the design will probably set precedence for any other plugin that wants to do the same.

### Problem Description

Right now, when configuring a discovery method in a server, gobetween only supports a single discovery:

```
  [servers.example.discovery]
  kind = "docker"
  docker_endpoint = "http://localhost:2375"
```

```
  [servers.example.discovery]
  kind = "json"
  json_endpoint = "http://localhost:8080"
```

```
  [servers.example.discovery]
  kind = "plaintext"
  plaintext_endpoint = "http://some.url.com"
```

```
  [servers.example.discovery]
  consul_host = "localhost:8500"
```

```
  [servers.example.discovery]
  kind = "lxd"
  lxd_server_address = "https://lxd-01.example.com:8443"   
```

For most of the plugins/drivers, a single discovery is acceptable. For example, `plaintext`, `json`, and `consul` can all contain data of backends which reside across multiple pieces of infrastructure (server, vm, containers, etc):

```
+---+    +---+     +---+
| G +--> | D +---> | B |
+---+    +-+-+     +---+
           |
           |       +---+
           +-----> | B |
           |       +---+
           |
           |       +---+
           +-----> | B |
                   +---+
```

But other discovery methods (LXD, Docker (#5), and [API](https://github.com/yyyar/gobetween/pull/95)) can only retrieve information from a single piece of infrastructure:

```
+---+    +-------+
| G +--> | D     |
+---+    |       |
         |    B  |
         |       |
         |    B  |
         |       |
         |    B  |
         +-------+
```

This effectively puts gobetween in a one-to-one relationship, which can be very limiting.

### Use Case

By having gobetween be able to query multiple discoveries, the one-to-one relationship can now be a one-to-many:

```
+---+    +-------+
| G +--> | D     |
+-+-+    |       |
  |      |    B  |
  |      |       |
  |      |    B  |
  |      |       |
  |      |    B  |
  |      +-------+
  |
  |      +-------+
  +----> | D     |
         |       |
         |    B  |
         |       |
         |    B  |
         +-------+
```

Depending on how this is implemented, not only would gobetween be able to query multiple endpoints of a specific discovery, but it could also query multiple _different_ discoveries.

### Possible Solutions

1. Use `json`, `plaintext`, `consul`, `dns`, etc instead. 

Using LXD as an example, when someone wants gobetween to talk to multiple LXD servers, stop using the LXD discovery and use `json`, `plaintext`, etc instead.

This is certainly a possible solution, but in my opinion, it's kind of weak. 

2. Make [`DiscoveryConfig`](https://github.com/yyyar/gobetween/blob/master/src/config/config.go#L98) a slice/array.

By doing this, multiple `[servers.example.discovery]` entries can be made in `gobetween.toml`. This solution is simple in theory but would require a large amount of changes internally. However, it would enable a lot of flexibility in what gobetween can do.

3. Handle this on a per-discovery basis.

Rather than implement a global solution, this would be dealt with on a per-discovery basis. Examples of this can be seen in https://github.com/yyyar/gobetween/pull/90. By doing this, gobetween would still be limited to one discovery per server, but at least now certain discovery plugins are no longer limited to the one-to-one relationship.

I'm interested to hear your thoughts on this. Additionally, I would be happy to help any way I can.

**Comment by nickdoikov** [comment]
Hello @jtopjian 
I thought about this feature several times last year . But there`s  some questions that need to be discovered before implementation will start .

How about consistency ?
Let`s assume that we have this feature, but all discoveries can and will respond asynchronous,
some of them can fail , also it will not possible to apply ```failpolicy```  to each sub-discovery , otherwise  total merged backend list can be  partially inconsistent.
This more about the logic then about implementation.   

There are  many  questions related to this feature .  Let`s discuss them   here.

**Comment by jtopjian** [comment]
@nickdoikov All good points.

> Let`s assume that we have this feature, but all discoveries can and will respond asynchronous,

Agreed. Multiple discoveries means distributed communication which means asynchronous which means anything can happen at any time. :)

> also it will not possible to apply failpolicy to each sub-discovery

The issue of repeatable configuration is a problem I first ran into with https://github.com/yyyar/gobetween/pull/90 (where I gave 4 examples of how to implement the configuration). By simply allowing _all_ configuration to be repeated, it's the simplest solution. 

But you are absolutely correct that certain items like `failpolicy` should not be repeated.

How about if there were global/master discovery configurations (which would be applied to all discoveries) and then per-discovery configurations (which would only handle the connection to the specific discovery).

If multiple discoveries are used, the simplest design would be to enforce `setempty` on a failed discovery. This would mark the entire discovery as untrustworthy/unhealthy. 

What if a discovery is so important that it can't be `setempty`? Make the discovery endpoint fault-tolerant so that communication is never interrupted. 

What if a discovery is known to fail? Add multiple discoveries so they can safely fail.

`setempty` by default makes sense in a lot of ways and closely follows modern design of expecting failure, but I admit that I might be missing important pieces.

> This more about the logic then about implementation.
> There are many questions related to this feature . Let`s discuss them here.

Agreed - this is why I closed #90 (and technically I could close #95 because it requires the same feature). This feature deserves careful thought and consideration.

**Comment by nickdoikov** [comment]
Probably we need to limit failpolicy to each sub discovery section  and leave multi discovery to currently discovered and merged list of backends.
Also we need to prevent single backend server:port to be added twice or more time from different sub discoveries(this is possible in some point).

@yyyar   what are you think about this?

**Comment by jtopjian** [comment]
@nickdoikov What do you mean by "sub discovery" and "multi discovery"? I might have the same concepts in mind, but might be thinking of them in different names.

> Also we need to prevent single backend server:port to be added twice or more time from different sub discoveries(this is possible in some point).

Agreed.

**Comment by yyyar** [comment]
Hi Everyone!
So what we can do is to introduce another discovery type: "composite", or "mixed", that holds a list of other discoveries. It would be backward compatible and will reuse most code we have.

```toml
[server.sample]
bind="0.0.0.0:3000"
protocol="tcp"

    [server.sample.discovery]
    kind="mixed"

        [[servers.sample.discovery.mixed]]
        kind = "static"
        static_list = [
            "localhost:8000",
            "localhost:8001"
        ]

        [[servers.sample.discovery.mixed]]
        kind = "docker"
        docker_endpoint = "http://localhost:2375"
        docker_container_private_port = 80

        # ... other
```
So it will allow simultaneous usage of many discoveries of different types (or even of the same type) at the same time.
 
Mixed discovery will have it's own failpolicy and other properties, as well as it's child discoveries. 
It's interval and timeout may be used as default values for child discoveries if they won't override these values.
Mixed discovery will get backends from child discoveries, merge them, and resolve backends conflicts and/or duplicates.

What do you think?

**Comment by jtopjian** [comment]
@yyyar It's a pretty clever solution :)

I like that it's able to keep the current plugin architecture and retain backwards compatibility.

Since one goal is to be able to define multiple same discoveries, would it be better to name it "multi"?

```toml
[server.sample]
bind="0.0.0.0:3000"
protocol="tcp"

    [server.sample.discovery]
    kind="multi"

        [[servers.example.discovery.multi]]
        kind = "lxd"
        lxd_server_address = "https://lxd-01.example.com:8443"   

        [[servers.example.discovery.multi]]
        kind = "lxd"
        lxd_server_address = "https://lxd-02.example.com:8443"   

        [[servers.sample.discovery.multi]]
        kind = "docker"
        docker_endpoint = "http://localhost:2375"
        docker_container_private_port = 80
```
