### ISSUE TITLE
after some time gobetween stops receive connections

### ISSUE THREAD

**Issue by nickdoikov** [yyyar/gobetween#13]
# netstat -anp |grep 9200 |wc -l
178

```json
{
    "active_connections": 6,
    "rx_total": 1562227305,
    "tx_total": 1724183714,
    "rx_second": 21308,
    "tx_second": 55111,
    "backends": [
        {
            "host": "10.0.0.53",
            "port": "9200",
            "priority": 1,
            "weight": 1,
            "stats": {
                "live": true,
                "total_connections": 9692,
                "active_connections": 1,
                "rx": 234993851,
                "tx": 133001288,
                "rx_second": 187,
                "tx_second": 318
            }
        },
        {
            "host": "10.0.0.54",
            "port": "9200",
            "priority": 1,
            "weight": 1,
            "stats": {
                "live": true,
                "total_connections": 9839,
                "active_connections": 1,
                "rx": 216484944,
                "tx": 131607080,
                "rx_second": 0,
                "tx_second": 491
            }
        },
        {
            "host": "10.0.0.55",
            "port": "9200",
            "priority": 1,
            "weight": 1,
            "stats": {
                "live": true,
                "total_connections": 9629,
                "active_connections": 1,
                "rx": 166526541,
                "tx": 2506771,
                "rx_second": 39,
                "tx_second": 32
            }
        },
        {
            "host": "10.0.0.51",
            "port": "9200",
            "priority": 1,
            "weight": 1,
            "stats": {
                "live": true,
                "total_connections": 9849,
                "active_connections": 2,
                "rx": 776211040,
                "tx": 1453758841,
                "rx_second": 34081,
                "tx_second": 80542
            }
        },
        {
            "host": "10.0.0.52",
            "port": "9200",
            "priority": 1,
            "weight": 1,
            "stats": {
                "live": true,
                "total_connections": 9508,
                "active_connections": 0,
                "rx": 168079725,
                "tx": 3470986,
                "rx_second": 39,
                "tx_second": 32
            }
        }
    ]
}
````

```toml
# dumped on 2016-07-13 04:55:44.270808288 +0000 UTC

[logging]
  level = "info"
  output = "/var/log/gobetween.log"

[api]
  enabled = true
  bind = "10.0.0.8:8888"

[defaults]
  max_connections = 0
  client_idle_timeout = "0"
  backend_idle_timeout = "0"
  backend_connection_timeout = "0"

[servers]
  [servers.elasticsearch]
    max_connections = 10000
    client_idle_timeout = "1m"
    backend_idle_timeout = "1m"
    backend_connection_timeout = "3m"
    bind = "10.0.0.8:9200"
    protocol = "tcp"
    balance = "weight"
    [servers.elasticsearch.discovery]
      kind = "static"
      failpolicy = "keeplast"
      interval = "0"
      timeout = "0"
      static_list = ["10.0.0.51:9200", "10.0.0.52:9200", "10.0.0.53:9200", "10.0.0.54:9200", "10.0.0.55:9200"]
    [servers.elasticsearch.healthcheck]
      kind = "ping"
      interval = "10s"
      passes = 3
      fails = 3
      timeout = "1s"
```

last logs
```log
2016-07-12 22:00:16 [INFO ] (proxy): read tcp 10.0.0.8:38724->10.0.0.53:9200: use of closed network connection
2016-07-12 22:00:18 [INFO ] (proxy): read tcp 10.0.0.8:38281->10.0.0.52:9200: use of closed network connection
2016-07-12 22:00:55 [INFO ] (proxy): read tcp 10.0.0.8:57795->10.0.0.55:9200: i/o timeout
2016-07-12 22:00:55 [INFO ] (proxy): read tcp 10.0.0.8:9200->10.0.0.60:45876: use of closed network connection
2016-07-12 22:01:13 [INFO ] (proxy): read tcp 10.0.0.8:59927->10.0.0.53:9200: i/o timeout
2016-07-12 22:01:13 [INFO ] (proxy): read tcp 10.0.0.8:9200->10.0.0.60:45347: use of closed network connection
2016-07-12 22:01:14 [INFO ] (proxy): read tcp 10.0.0.8:35520->10.0.0.54:9200: i/o timeout
2016-07-12 22:01:14 [INFO ] (proxy): read tcp 10.0.0.8:9200->10.0.0.60:45348: use of closed network connection
2016-07-12 22:01:18 [INFO ] (proxy): read tcp 10.0.0.8:9200->10.0.0.60:45344: i/o timeout
2016-07-12 22:01:19 [INFO ] (proxy): read tcp 10.0.0.8:9200->10.0.0.60:45345: i/o timeout
```
