### ISSUE TITLE
Error: dial tcp :0: getsockopt: connection refused

### ISSUE THREAD

**Issue by honzatrtik** [yyyar/gobetween#46]
Hello,
Im trying gobetween on my dev machine - Im using `docker-machine` & `boot2docker (1.12.3)`

This is my simple docker compose:
```yaml
version: '2'

networks:
  backend:

services:
  app:
    image: php:7.0-alpine
    expose:
      - 8080
    volumes:
      - .:/data
    command: php -S 0.0.0.0:8080 /data/index.php
    networks:
      - backend
    labels:
      - "scale.app=true"

  gobetween:
    image: yyyar/gobetween
    depends_on:
      - app
    ports:
      - "80:80"
    volumes:
      - "./gobetween/conf:/etc/gobetween/conf/:rw"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - backend
```

Gobetween conf looks like this:

```ini
[logging]
level = "debug"

[servers.app]
bind = "0.0.0.0:80"
protocol = "tcp"
balance = "roundrobin"

  [servers.app.discovery]
    interval = "10s"
    timeout = "2s"
    kind = "docker"
    docker_endpoint = "unix://var/run/docker.sock"  # Docker / Swarm API
    docker_container_label = "scale.app=true"  # label to filter containers
    docker_container_private_port = 8080   # gobetween will take public container port for this private port
    docker_container_host_env_var = "HOSTNAME"
```

Gobetween is able to discover new backends, when i try to scale up the app, but proxying is not working - see log output:

```sh
app_1        | PHP 7.0.13 Development Server started at Fri Nov 25 20:08:30 2016
gobetween_1  | 2016-11-25 20:08:31 [INFO ] (manager): Initializing...
gobetween_1  | 2016-11-25 20:08:31 [INFO ] (server): Creating 'app': 0.0.0.0:80 roundrobin docker none
gobetween_1  | 2016-11-25 20:08:31 [INFO ] (scheduler): Starting scheduler
gobetween_1  | 2016-11-25 20:08:31 [INFO ] (manager): Initialized
gobetween_1  | 2016-11-25 20:08:31 [INFO ] (api): API disabled
gobetween_1  | 2016-11-25 20:08:31 [INFO ] (dockerFetch): Fetching unix://var/run/docker.sock scale.app=true 8080
gobetween_1  | 2016-11-25 20:08:40 [DEBUG] (server.handle): Accepted 10.211.55.2:52649 -> [::]:80
gobetween_1  | 2016-11-25 20:08:40 [DEBUG] (server.handle): Accepted 10.211.55.2:52648 -> [::]:80
gobetween_1  | 2016-11-25 20:08:40 [ERROR] (server.handle): dial tcp :0: getsockopt: connection refused
gobetween_1  | 2016-11-25 20:08:40 [ERROR] (server.handle): dial tcp :0: getsockopt: connection refused
```

Am I missing something?

**Comment by nickdoikov** [comment]
``` 
docker_container_host_env_var = "HOSTNAME"
```
do you have such env var  in scale.app containers ?

**Comment by illarion** [comment]
@honzatrtik Thank you for the report, I'll try to reproduce.

**Comment by honzatrtik** [comment]
Yup, this env var is set by docker-compose
```sh
scale-test git:(master) ✗ docker exec scaletest_app_1 env

PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
HOSTNAME=939c5b6ac993
PHPIZE_DEPS=autoconf 		file 		g++ 		gcc 		libc-dev 		make 		pkgconf 		re2c
PHP_INI_DIR=/usr/local/etc/php
...
```

Anyway it was the same if `docker_container_host_env_var ` was not present in config...

**Comment by nickdoikov** [comment]
we are investigating this issue

**Comment by illarion** [comment]
@honzatrtik when I run docker inspect on your container, I don't see HOSTNAME env there:

  ```
         "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "PHPIZE_DEPS=autoconf \t\tfile \t\tg++ \t\tgcc \t\tlibc-dev \t\tmake \t\tpkgconf \t\tre2c",
                "PHP_INI_DIR=/usr/local/etc/php",
                "GPG_KEYS=1A4E8B7277C42E53DBA9C7B9BCAA30EA9C0D5763",
                "PHP_VERSION=7.0.13",
                "PHP_URL=https://secure.php.net/get/php-7.0.13.tar.xz/from/this/mirror",
                "PHP_ASC_URL=https://secure.php.net/get/php-7.0.13.tar.xz.asc/from/this/mirror",
                "PHP_SHA256=357ba7f93975d7d836abed0852dc3ed96a988af539e87750613294cbee82f1bf",
                "PHP_MD5=eb117bf1d1efc99c522f132b265a3402"
            ],

```

**Comment by honzatrtik** [comment]
@illarion according to docs the `HOSTNAME` env var is created by docker engine itself when container is run - https://docs.docker.com/engine/reference/run/#/env-environment-variables
the funny part is that this var is not shown in `docker inspect`  😕

**Comment by nickdoikov** [comment]
@honzatrtik
there is no possibility for now use gobetween without exposed ports in Docker.
main idea of usage gobetween - to be an ingress for an external traffic for pool of servers in swarm.
you can use it with random ports . i will create compose file for you soon .

**Comment by nickdoikov** [comment]
i have added my docker host ip . feel free to use your`s 

```yaml
version: '2'

networks:
  backend:

services:
  app:
    image: php:7.0-alpine
    ports:
      - "8080"
    volumes:
      - .:/data
    command: php -S 0.0.0.0:8080 /data/index.php
    networks:
      - backend
    labels:
      - "scale.app=true"
    environment:
      - HOST_IP=192.168.1.106

  gobetween:
    image: yyyar/gobetween
    depends_on:
      - app
    ports:
      - "80:80"
    volumes:
      - "./gobetween/conf:/etc/gobetween/conf/:rw"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - backend
```

```toml
[logging]
level = "debug"

[servers.app]
bind = "0.0.0.0:80"
protocol = "tcp"
balance = "roundrobin"

  [servers.app.discovery]
    interval = "10s"
    timeout = "2s"
    kind = "docker"
    docker_endpoint = "unix:///var/run/docker.sock"  # Docker / Swarm API
    docker_container_label = "scale.app=true"  # label to filter containers
    docker_container_private_port = 8080   # gobetween will take public container port for this private port
    docker_container_host_env_var = "HOST_IP"
```


at the end

```bash
nick$ curl http://192.168.1.106
test
```
