### ISSUE TITLE
Drop [optionally] connections / sessions to dead backends

### ISSUE THREAD

**Issue by illarion** [yyyar/gobetween#74]
## Description
Gobetween keeps "session" connecting client (source_host:port) and backend (host:port) until it times out or closes or fails to read/write. It may be not enough, if session is targeting backend that is actually dead and failing healthchecks.

### UDP
Udp is sessionless, so that in very many cases client is not aware that server have stopped receiving udp packets. It would be nice if new packets from such client will be routed to another backend that is live.

### TCP
As the result of bugs on backend side, it can get stuck -- keeping tcp session open and even reading data from it, but not processing it. In such case failed healthcheck would drop such connection forcing client to reconnect

### Proposed config
```
 [servers.default.healthcheck]   # (optional)
...
force_disconnect = false # optional, if true - drop connections to backends that didn't pass healthcheck
```

Thanks: @theairkit for initial problem description and pull request

**Comment by theairkit** [comment]
@illarion 
What you think about adding that options to [servers.default.[tcp|udp]]:
- healthcheck section may be absent: it is optional section, and user may used discovery only
([servers.defaults.discovery] with any discovery method - static, exec, etc.), but wants to set this behavoir;
- split this this TCP- and UDP-behavior to each [server.$servername.[tcp|udp]] directly allows more flexible and clear configuration (i.e. for one server set to defaults, for other - force_disconnect);

So, what you think about this proposed config?
```toml
[servers.default.tcp] # (optional)
...
force_disconnect = false # optional, if true - drop connections to backends that did not response
...
[servers.default.udp] # (optional)
...
force_disconnect = false # optional, if true - drop connections to backends that did not response or did not discovered on next check
```

Thanks!
